In [1]:
import numpy as np
ft = np.array([1,2,3,4])
print(ft)

[1 2 3 4]


In [2]:
arr_zer = np.zeros((3,3))
print(arr_zer)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
array_ones = np.ones((4,4))
print(array_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr_empt = np.empty((5,5))
print(arr_empt)

[[6.23042070e-307 3.56043053e-307 1.60219306e-306 7.56571288e-307
  1.89146896e-307]
 [1.37961302e-306 1.05699242e-307 8.01097889e-307 1.78020169e-306
  7.56601165e-307]
 [1.02359984e-306 1.11259940e-306 1.11261774e-306 1.78019625e-306
  1.11261774e-306]
 [1.78019625e-306 1.11261774e-306 1.78019625e-306 1.24610994e-306
  1.11261570e-306]
 [1.37961302e-306 1.11260280e-306 8.34451079e-308 8.34402698e-308
  3.91792476e-317]]


In [12]:
np_arrange = np.arange(12)
print(np_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
np_arrange.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np_linspace = np.linspace(1,2,3)
print(np_linspace)

[1.  1.5 2. ]


In [18]:
one_d_array = np.arange(15)
print(one_d_array)
two_d_arr = one_d_array.reshape(3,5)
print(two_d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [19]:
three_d_array = np.arange(27).reshape(3,3,3)
print(three_d_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [20]:
np.add(45,20)

65

In [22]:
np_daily_wage_hr = np.array([4,5,6,7,8])*15
print(np_daily_wage_hr)

[ 60  75  90 105 120]


In [25]:
sum(np_daily_wage_hr)

450

In [33]:
np_weekly_hrs = np.array([39, 40,45,46,50])

#np_weekly_hrs[np_weekly_hrs>40]

np_weekly_hrs[np_weekly_hrs!=40]

#greater_one = [np_weekly_hrs > 40]

#print(greater_one)

array([39, 45, 46, 50])

In [35]:
np.logical_and(np_weekly_hrs>40, np_weekly_hrs<50)

array([False, False,  True,  True, False])

In [16]:
import numpy as np
countries = np.array(['Algeria','Angola','Argentina','Australia','Austria','Bahamas','Bangladesh','Belarus','Belgium','Bhutan','Brazil','Bulgaria','Cambodia','Cameroon','Chile','China','Colombia','Cyprus','Denmark','El Salvador','Estonia','Ethiopia','Fiji','Finland','France','Georgia','Ghana','Grenada','Guinea','Haiti','Honduras','Hungary','India','Indonesia','Ireland','Italy','Japan','Kenya', 'South Korea','Liberia','Malaysia','Mexico', 'Morocco','Nepal','New Zealand','Norway','Pakistan', 'Peru','Qatar','Russia','Singapore','South Africa','Spain','Sweden','Switzerland','Thailand', 'United Arab Emirates','United Kingdom','United States','Uruguay','Venezuela','Vietnam','Zimbabwe'
])
GDP = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,5671.912202,757.4009286,347.7456605])

maxm = GDP.argmax()
maxm
country_max_gdp = countries[maxm]
country_max_gdp

'Norway'

In [19]:
minm = GDP.argmin()
country_min_gdp = countries[minm]
country_min_gdp


'Ethiopia'

In [23]:
for country in countries: 
    print('countries name are {}'.format(country))

countries name are Algeria
countries name are Angola
countries name are Argentina
countries name are Australia
countries name are Austria
countries name are Bahamas
countries name are Bangladesh
countries name are Belarus
countries name are Belgium
countries name are Bhutan
countries name are Brazil
countries name are Bulgaria
countries name are Cambodia
countries name are Cameroon
countries name are Chile
countries name are China
countries name are Colombia
countries name are Cyprus
countries name are Denmark
countries name are El Salvador
countries name are Estonia
countries name are Ethiopia
countries name are Fiji
countries name are Finland
countries name are France
countries name are Georgia
countries name are Ghana
countries name are Grenada
countries name are Guinea
countries name are Haiti
countries name are Honduras
countries name are Hungary
countries name are India
countries name are Indonesia
countries name are Ireland
countries name are Italy
countries name are Japan
count

In [33]:
#print countries and their GDP 

for i in zip(countries, GDP): 
    print("Country {} has per capita GDP of {}". format(i[0],i[1]))

Country Algeria has per capita GDP of 2255.225482
Country Angola has per capita GDP of 629.9553062
Country Argentina has per capita GDP of 11601.63022
Country Australia has per capita GDP of 25306.82494
Country Austria has per capita GDP of 27266.40335
Country Bahamas has per capita GDP of 19466.99052
Country Bangladesh has per capita GDP of 588.3691778
Country Belarus has per capita GDP of 2890.345675
Country Belgium has per capita GDP of 24733.62696
Country Bhutan has per capita GDP of 1445.760002
Country Brazil has per capita GDP of 4803.398244
Country Bulgaria has per capita GDP of 2618.876037
Country Cambodia has per capita GDP of 590.4521124
Country Cameroon has per capita GDP of 665.7982328
Country Chile has per capita GDP of 7122.938458
Country China has per capita GDP of 2639.54156
Country Colombia has per capita GDP of 3362.4656
Country Cyprus has per capita GDP of 15378.16704
Country Denmark has per capita GDP of 30860.12808
Country El Salvador has per capita GDP of 2579.115

In [27]:
mean_gdp = GDP.mean()
mean_gdp

11289.409271639683

In [28]:
sum_GDP = GDP.sum()
sum_GDP

711232.7841133

In [36]:
print(GDP.std())

12743.828910617945


In [72]:
#Analyse London Olympics Dataset
import numpy as np
import pandas as pd

df = pd.read_excel('Olympic.xlsx', index_col=0)
df.head
#to_drop = ['Unnamed: 1', 'Unnamed: 2']
#df.drop(head, inplace=True, axis=1)
#df

<bound method NDFrame.head of         Unnamed: 1    Unnamed: 2 Unnamed: 3   Unnamed: 4 Unnamed: 5 Unnamed: 6
NaN        Country  Country Code       Year  Medal Tally        NaN        NaN
NaN            NaN           NaN        NaN         Gold     Silver     Bronze
NaN  Great Britain           GBR       2012           29         17         19
NaN         China            CHN       2012           38         28         22
NaN         Russia           RUS       2012           24         25         32
NaN  United States            US       2012           46         28         29
NaN          Korea           KOR       2012           13          8          7
NaN          Japan           JPN       2012            7         14         17
NaN        Germany           GER       2012           11         11         14>

In [73]:
import numpy as np

olympic_country_dataset = np.array(['GBR', 'CHN', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
olympic_gold = np.array([29, 38, 24, 46, 13, 7, 11])
olympic_silver = np.array([17,28,25,28,8,14,11])
olympic_bronze = np.array([19,22,32,29,7,17,14])

max_gold = olympic_gold.argmax()
country_max_gold = olympic_country_dataset[max_gold]
country_max_gold

'US'

In [76]:
for i in zip(olympic_country_dataset, olympic_gold):
    if i[1] > 20:
        print('the countries with more than 20 medals are {} with {} gold medals' . format(i[0], i[1]))

the countries with more than 20 medals are GBR with 29 gold medals
the countries with more than 20 medals are CHN with 38 gold medals
the countries with more than 20 medals are RUS with 24 gold medals
the countries with more than 20 medals are US with 46 gold medals


In [77]:
for i in zip(olympic_country_dataset, olympic_gold, olympic_silver, olympic_bronze): 
    print(' the medal tally of country {} for gold is {}, silver {} and  bronze {} respectively'. format(i[0], i[1], i[2], i[3]))

 the medal tally of country GBR for gold is 29, for silver 17 and for bronze 19 respectively
 the medal tally of country CHN for gold is 38, for silver 28 and for bronze 22 respectively
 the medal tally of country RUS for gold is 24, for silver 25 and for bronze 32 respectively
 the medal tally of country US for gold is 46, for silver 28 and for bronze 29 respectively
 the medal tally of country KOR for gold is 13, for silver 8 and for bronze 7 respectively
 the medal tally of country JPN for gold is 7, for silver 14 and for bronze 17 respectively
 the medal tally of country GER for gold is 11, for silver 11 and for bronze 14 respectively


In [85]:
a = olympic_gold.sum()
b = olympic_silver.sum()
c = olympic_bronze.sum()

print (" the total number of medal tally is {}". format(a+b+c))

 the total number of medal tally is 439
