In [ ]:
#Integration

In [2]:
from scipy.integrate import quad
def integrateFunction(x):
    return x

quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [4]:
def integrateFn(x,a,b):
    return x*a+b

a=3
b=2
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [5]:
#multiple integration

import scipy.integrate as integrate
def f(x,y):
    return x+y
integrate.dblquad(f, 0,1, lambda x: 0, lambda x: 2)

(3.0, 4.436070580899685e-14)

In [6]:
#optimizzation

import numpy as np
from scipy import optimize

def f(x):
    return x*x + 5*np.sin(x)

minimalvalue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 27
         Gradient evaluations: 9


In [8]:
minimumvalue_without_options = optimize.minimize(f,x0=2, method='bfgs')
minimumvalue_without_options

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 27
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [10]:
#optimize root function

import numpy as np
from scipy.optimize import root
def rootfunc(x):
    return x + 3.5 * np.cos(x)

rootvalue = root(rootfunc, 0.3)
rootvalue
    

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

In [11]:
#linear algebra
#inverse of matrix

import numpy as np
from scipy import linalg

matrix = np.array([[10,6], [5,7]])
matrix

array([[10,  6],
       [ 5,  7]])

In [13]:
linalg.inv(matrix)

array([[ 0.175, -0.15 ],
       [-0.125,  0.25 ]])

In [14]:
# finding determinant

linalg.det(matrix)

40.0

In [15]:
# solve linear systems

import numpy as np
from scipy import linalg

numarray = np.array([[2,3,1], [-1,5,4], [3,2,9]])
numaarayvalue = np.array([1,2,3])
linalg.solve(numarray, numaarayvalue)

array([0.06666667, 0.2       , 0.26666667])

In [17]:
# Single value decomposition (SVD)

import numpy as np
from scipy import linalg

numsvdarr = np.array([[1,2,3], [4,5,6]])

linalg.svd(numsvdarr)

(array([[-0.3863177 , -0.92236578],
        [-0.92236578,  0.3863177 ]]),
 array([9.508032  , 0.77286964]),
 array([[-0.42866713, -0.56630692, -0.7039467 ],
        [ 0.80596391,  0.11238241, -0.58119908],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [20]:
#calculate eigen value and eigen vector

import numpy as np
from scipy import linalg

test_rating_data = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = linalg.eig(test_rating_data)


(-0.3722813232690143+0j) (5.372281323269014+0j)


In [24]:
#print first and second eigenvectors
print(eigenvectors[:,0])
print(eigenvectors[:,1])

[-0.82456484  0.56576746]
[-0.41597356 -0.90937671]


In [23]:
#print eigenvalues
first_eigen, second_eigen = eigenvalues
print(first_eigen, second_eigen)

(-0.3722813232690143+0j) (5.372281323269014+0j)


In [25]:
#statistics
#normal distribution

from scipy.stats import norm
norm.rvs(loc=0,scale=1,size=10)

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


array([-0.51767789,  0.6759547 , -1.18875783, -0.25225744, -0.9636725 ,
       -0.97677306, -1.31349378,  1.51165481,  0.43465197, -0.70459004])

In [26]:
#cummulative distributive function
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [28]:
probability density function
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18